# Generated by Django 5.0.4 on 2024-05-04 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='svgimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='svgimage',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 14, 47, 11, 194104, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='svgimage',
            name='tags',
            field=models.ManyToManyField(blank=True, to='polls.tag'),
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
